<a href="https://colab.research.google.com/github/harshbhabhera/Home-Assignment/blob/master/TextBlob.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np


In [0]:
twitter = pd.read_csv("https://raw.githubusercontent.com/zfz/twitter_corpus/master/full-corpus.csv", sep=',')
amazon = pd.read_json("http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Office_Products_5.json.gz", lines=True)
amazon = amazon.iloc[0:200,:]

In [19]:
!pip install -U textblob
! python -m textblob.download_corpora

Requirement already up-to-date: textblob in /usr/local/lib/python3.6/dist-packages (0.15.3)
[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package conll2000 to /root/nltk_data...
[nltk_data]   Package conll2000 is already up-to-date!
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!
Finished.


In [20]:
import pandas as pd
from textblob import TextBlob
from nltk.sentiment.vader import SentimentIntensityAnalyzer as SIA
import nltk
nltk.download('vader_lexicon') 
from sklearn.metrics import confusion_matrix, accuracy_score

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


In [21]:
twitter

Topic  ...                                          TweetText
0       apple  ...  Now all @Apple has to do is get swype on the i...
1       apple  ...  @Apple will be adding more carrier support to ...
2       apple  ...  Hilarious @youtube video - guy does a duet wit...
3       apple  ...  @RIM you made it too easy for me to switch to ...
4       apple  ...  I just realized that the reason I got into twi...
...       ...  ...                                                ...
5108  twitter  ...                            me re copè con #twitter
5109  twitter  ...  Buenas noches genteeee :) #twitter los quieroo...
5110  twitter  ...  #twitter tiene la mala costumbre de ponerce bn...
5111  twitter  ...  Oi @flaviasansi. Muito bem vinda ao meu #Twitt...
5112  twitter  ...  Eles arrastaram os barcos para a praia, deixar...

[5113 rows x 5 columns]

In [22]:
amazon.head(5)

reviewerID        asin  ... unixReviewTime   reviewTime
0  A32T2H8150OJLU  B00000JBLH  ...     1094169600   09 3, 2004
1  A3MAFS04ZABRGO  B00000JBLH  ...     1197676800  12 15, 2007
2  A1F1A0QQP2XVH5  B00000JBLH  ...     1293840000   01 1, 2011
3   A49R5DBXXQDE5  B00000JBLH  ...     1145404800  04 19, 2006
4  A2XRMQA6PJ5ZJ8  B00000JBLH  ...     1375574400   08 4, 2013

[5 rows x 9 columns]

In [23]:
blob = TextBlob("good bell")
blob.sentiment

Sentiment(polarity=0.7, subjectivity=0.6000000000000001)

In [24]:
twitter = twitter[twitter['Sentiment'] != "irrelevant"]
twitter['Sentiment'].value_counts()

neutral     2333
negative     572
positive     519
Name: Sentiment, dtype: int64

In [0]:
def blob(stri):
  senttextblob = TextBlob(stri).sentiment
  poltextblob = senttextblob.polarity
  if poltextblob > 0.0:
    return "positive"
  elif poltextblob == 0.0:
    return "neutral"
  else:
    return "negative"

In [0]:
def nltk_(stri):
  s = SIA()
  sn = s.polarity_scores(stri)
  #return sn
  if sn['compound'] >= 0.05:
    return "positive"
  elif -0.05 < sn['compound'] < 0.05:
    return "neutral"
  else:
    return "negative"

In [27]:
twitter['sent_nltk'] = twitter['TweetText'].apply(nltk_)
twitter['sent_blob'] = twitter['TweetText'].apply(blob)
twitter.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Topic Sentiment  ...  sent_nltk sent_blob
0  apple  positive  ...    neutral   neutral
1  apple  positive  ...   positive  positive
2  apple  positive  ...   positive  positive
3  apple  positive  ...   positive  positive
4  apple  positive  ...   positive  positive

[5 rows x 7 columns]

In [28]:
amazon['sent_nltk'] = amazon['reviewText'].apply(nltk_)
amazon['sent_blob'] = amazon['reviewText'].apply(blob)
amazon.head()

reviewerID        asin  ... sent_nltk sent_blob
0  A32T2H8150OJLU  B00000JBLH  ...  positive  positive
1  A3MAFS04ZABRGO  B00000JBLH  ...  positive  positive
2  A1F1A0QQP2XVH5  B00000JBLH  ...  negative  positive
3   A49R5DBXXQDE5  B00000JBLH  ...  positive  positive
4  A2XRMQA6PJ5ZJ8  B00000JBLH  ...  positive  positive

[5 rows x 11 columns]

In [0]:
nltk_matrix = confusion_matrix(twitter['Sentiment'], twitter['sent_nltk'])
blob_matrix = confusion_matrix(twitter['Sentiment'], twitter['sent_blob'])
nltk_acc = accuracy_score(twitter['Sentiment'], twitter['sent_nltk'])
blob_acc = accuracy_score(twitter['Sentiment'], twitter['sent_blob'])


In [30]:
print("NLTK confusion matrix is: ")
print(nltk_matrix)
print("NLTK accuracy is: ", nltk_acc)


NLTK confusion matrix is: 
[[ 291  138  143]
 [ 302 1234  797]
 [  47   99  373]]
NLTK accuracy is:  0.554322429906542


In [31]:

print("TextBlob confusion matrix is: ")
print(blob_matrix)
print("TextBlob accuracy is: ", blob_acc)

TextBlob confusion matrix is: 
[[ 234  171  167]
 [ 201 1213  919]
 [  38  124  357]]
TextBlob accuracy is:  0.5268691588785047


In [0]:
######################

In [39]:
nltk.download('punkt')
# issue importing glove

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [0]:
tokens = twitter.TweetText.apply(nltk.word_tokenize)      
corpus = Corpus()                                   
corpus.fit(tokens, window=10)                        

In [0]:
glove = Glove(no_components=100, learning_rate=0.05)
glove.fit(corpus.matrix, epochs=30, no_threads=4, verbose=True)

In [0]:
glove.add_dictionary(corpus.dictionary)
glove.most_similar('amazing')